version: 0.0
os: linux
files:
  - source: src/
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: hooks/BeforeInstall.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: hooks/AfterInstall.sh
      timeout: 60
      runas: root